//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bb.Parsers.TSql
{
    using System;
    using Bb.Parsers;
    using Bb.Asts.TSql;
    using Bb.Asts;
    using Bb.Parsers.TSql.Antlr;
    using Antlr4.Runtime.Misc;
    using Antlr4.Runtime.Tree;
    using System.Collections;
    
    
    public partial class ScriptTSqlVisitor
    {
        
        /// <summary>
        /// binary_content_nexts
        /// 	 : binary_content_next+
        /// </summary>
        public override AstRoot VisitBinary_content_nexts(TSqlParser.Binary_content_nextsContext context)
        {
            TSqlParser.Binary_content_nextContext[] source = context.binary_content_next();
            AstBinaryContentNexts list = new AstBinaryContentNexts(context, source.Length);
            for (IEnumerator enumerator = source.GetEnumerator(); enumerator.MoveNext(); 
            )
            {
                TSqlParser.Binary_content_nextContext item = ((TSqlParser.Binary_content_nextContext)(enumerator.Current));
                AstBinaryContentNext acceptResult = ((AstBinaryContentNext)(item.Accept(this)));
                if ((acceptResult != null))
                {
                    list.Add(acceptResult);
                }
            }
            return list;
        }
        
        /// <summary>
        /// sybase_legacy_hints
        /// 	 : sybase_legacy_hint+
        /// </summary>
        public override AstRoot VisitSybase_legacy_hints(TSqlParser.Sybase_legacy_hintsContext context)
        {
            TSqlParser.Sybase_legacy_hintContext[] source = context.sybase_legacy_hint();
            AstSybaseLegacyHints list = new AstSybaseLegacyHints(context, source.Length);
            for (IEnumerator enumerator = source.GetEnumerator(); enumerator.MoveNext(); 
            )
            {
                TSqlParser.Sybase_legacy_hintContext item = ((TSqlParser.Sybase_legacy_hintContext)(enumerator.Current));
                AstSybaseLegacyHint acceptResult = ((AstSybaseLegacyHint)(item.Accept(this)));
                if ((acceptResult != null))
                {
                    list.Add(acceptResult);
                }
            }
            return list;
        }
    }
}
