//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bb.Asts {
    using System;
    using Bb.Asts;
    
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visittsql_file(Asttsql_file i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitbatch(Astbatch i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitbatch_level_statement(Astbatch_level_statement i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitsql_clauses(Astsql_clauses i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdml_clause(Astdml_clause i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitddl_clause(Astddl_clause i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitbackup_statement(Astbackup_statement i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcfl_statement(Astcfl_statement i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitblock_statement(Astblock_statement i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitbreak_statement(Astbreak_statement i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcontinue_statement(Astcontinue_statement i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitgoto_statement(Astgoto_statement i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitreturn_statement(Astreturn_statement i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitif_statement(Astif_statement i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitthrow_statement(Astthrow_statement i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitthrow_error_number(Astthrow_error_number i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitthrow_message(Astthrow_message i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitthrow_state(Astthrow_state i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visittry_catch_statement(Asttry_catch_statement i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitwaitfor_statement(Astwaitfor_statement i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitwhile_statement(Astwhile_statement i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitprint_statement(Astprint_statement i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitraiseerror_statement(Astraiseerror_statement i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitempty_statement(Astempty_statement i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitanother_statement(Astanother_statement i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_application_role(Astalter_application_role i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_application_role(Astcreate_application_role i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_aggregate(Astdrop_aggregate i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_application_role(Astdrop_application_role i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_assembly(Astalter_assembly i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_assembly_start(Astalter_assembly_start i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_assembly_clause(Astalter_assembly_clause i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_assembly_from_clause(Astalter_assembly_from_clause i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_assembly_from_clause_start(Astalter_assembly_from_clause_start i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_assembly_drop_clause(Astalter_assembly_drop_clause i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_assembly_drop_multiple_files(Astalter_assembly_drop_multiple_files i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_assembly_drop(Astalter_assembly_drop i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_assembly_add_clause(Astalter_assembly_add_clause i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_asssembly_add_clause_start(Astalter_asssembly_add_clause_start i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_assembly_client_file_clause(Astalter_assembly_client_file_clause i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_assembly_file_name(Astalter_assembly_file_name i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_assembly_file_bits(Astalter_assembly_file_bits i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_assembly_as(Astalter_assembly_as i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_assembly_with_clause(Astalter_assembly_with_clause i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_assembly_with(Astalter_assembly_with i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitclient_assembly_specifier(Astclient_assembly_specifier i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitassembly_option(Astassembly_option i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitnetwork_file_share(Astnetwork_file_share i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitnetwork_computer(Astnetwork_computer i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitnetwork_file_start(Astnetwork_file_start i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitfile_path(Astfile_path i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitfile_directory_path_separator(Astfile_directory_path_separator i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitlocal_file(Astlocal_file i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitlocal_drive(Astlocal_drive i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitmultiple_local_files(Astmultiple_local_files i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitmultiple_local_file_start(Astmultiple_local_file_start i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_assembly(Astcreate_assembly i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_assembly(Astdrop_assembly i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_asymmetric_key(Astalter_asymmetric_key i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_asymmetric_key_start(Astalter_asymmetric_key_start i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitasymmetric_key_option(Astasymmetric_key_option i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitasymmetric_key_option_start(Astasymmetric_key_option_start i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitasymmetric_key_password_change_option(Astasymmetric_key_password_change_option i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_asymmetric_key(Astcreate_asymmetric_key i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_asymmetric_key(Astdrop_asymmetric_key i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_authorization(Astalter_authorization i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitauthorization_grantee(Astauthorization_grantee i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitentity_to(Astentity_to i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcolon_colon(Astcolon_colon i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_authorization_start(Astalter_authorization_start i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_authorization_for_sql_database(Astalter_authorization_for_sql_database i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_authorization_for_azure_dw(Astalter_authorization_for_azure_dw i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_authorization_for_parallel_dw(Astalter_authorization_for_parallel_dw i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitclass_type(Astclass_type i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitclass_type_for_sql_database(Astclass_type_for_sql_database i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitclass_type_for_azure_dw(Astclass_type_for_azure_dw i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitclass_type_for_parallel_dw(Astclass_type_for_parallel_dw i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitclass_type_for_grant(Astclass_type_for_grant i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_availability_group(Astdrop_availability_group i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_availability_group(Astalter_availability_group i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_availability_group_start(Astalter_availability_group_start i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_availability_group_options(Astalter_availability_group_options i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitip_v4_failover(Astip_v4_failover i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitip_v6_failover(Astip_v6_failover i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_or_alter_broker_priority(Astcreate_or_alter_broker_priority i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_broker_priority(Astdrop_broker_priority i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_certificate(Astalter_certificate i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_column_encryption_key(Astalter_column_encryption_key i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_column_encryption_key(Astcreate_column_encryption_key i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_certificate(Astdrop_certificate i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_column_encryption_key(Astdrop_column_encryption_key i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_column_master_key(Astdrop_column_master_key i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_contract(Astdrop_contract i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_credential(Astdrop_credential i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_cryptograhic_provider(Astdrop_cryptograhic_provider i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_database(Astdrop_database i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_database_audit_specification(Astdrop_database_audit_specification i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_database_encryption_key(Astdrop_database_encryption_key i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_database_scoped_credential(Astdrop_database_scoped_credential i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_default(Astdrop_default i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_endpoint(Astdrop_endpoint i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_external_data_source(Astdrop_external_data_source i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_external_file_format(Astdrop_external_file_format i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_external_library(Astdrop_external_library i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_external_resource_pool(Astdrop_external_resource_pool i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_external_table(Astdrop_external_table i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_event_notifications(Astdrop_event_notifications i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_event_session(Astdrop_event_session i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_fulltext_catalog(Astdrop_fulltext_catalog i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_fulltext_index(Astdrop_fulltext_index i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_fulltext_stoplist(Astdrop_fulltext_stoplist i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_login(Astdrop_login i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_master_key(Astdrop_master_key i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_message_type(Astdrop_message_type i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_partition_function(Astdrop_partition_function i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_partition_scheme(Astdrop_partition_scheme i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_queue(Astdrop_queue i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_remote_service_binding(Astdrop_remote_service_binding i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_resource_pool(Astdrop_resource_pool i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_db_role(Astdrop_db_role i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_route(Astdrop_route i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_rule(Astdrop_rule i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_schema(Astdrop_schema i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_search_property_list(Astdrop_search_property_list i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_security_policy(Astdrop_security_policy i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_sequence(Astdrop_sequence i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_server_audit(Astdrop_server_audit i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_server_audit_specification(Astdrop_server_audit_specification i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_server_role(Astdrop_server_role i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_service(Astdrop_service i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_signature(Astdrop_signature i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_statistics_name_azure_dw_and_pdw(Astdrop_statistics_name_azure_dw_and_pdw i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_symmetric_key(Astdrop_symmetric_key i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_synonym(Astdrop_synonym i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_user(Astdrop_user i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_workload_group(Astdrop_workload_group i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_xml_schema_collection(Astdrop_xml_schema_collection i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdisable_trigger(Astdisable_trigger i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitenable_trigger(Astenable_trigger i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitlock_table(Astlock_table i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visittruncate_table(Asttruncate_table i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_column_master_key(Astcreate_column_master_key i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_credential(Astalter_credential i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_credential(Astcreate_credential i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_cryptographic_provider(Astalter_cryptographic_provider i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_cryptographic_provider(Astcreate_cryptographic_provider i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_event_notification(Astcreate_event_notification i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_or_alter_event_session(Astcreate_or_alter_event_session i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitevent_session_predicate_expression(Astevent_session_predicate_expression i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitevent_session_predicate_factor(Astevent_session_predicate_factor i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitevent_session_predicate_leaf(Astevent_session_predicate_leaf i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_external_data_source(Astalter_external_data_source i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_external_library(Astalter_external_library i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_external_library(Astcreate_external_library i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_external_resource_pool(Astalter_external_resource_pool i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_external_resource_pool(Astcreate_external_resource_pool i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_fulltext_catalog(Astalter_fulltext_catalog i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_fulltext_catalog(Astcreate_fulltext_catalog i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_fulltext_stoplist(Astalter_fulltext_stoplist i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_fulltext_stoplist(Astcreate_fulltext_stoplist i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_login_sql_server(Astalter_login_sql_server i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_login_sql_server(Astcreate_login_sql_server i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_login_azure_sql(Astalter_login_azure_sql i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_login_azure_sql(Astcreate_login_azure_sql i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_login_azure_sql_dw_and_pdw(Astalter_login_azure_sql_dw_and_pdw i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_login_pdw(Astcreate_login_pdw i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_master_key_sql_server(Astalter_master_key_sql_server i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_master_key_sql_server(Astcreate_master_key_sql_server i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_master_key_azure_sql(Astalter_master_key_azure_sql i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_master_key_azure_sql(Astcreate_master_key_azure_sql i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_message_type(Astalter_message_type i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_partition_function(Astalter_partition_function i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_partition_scheme(Astalter_partition_scheme i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_remote_service_binding(Astalter_remote_service_binding i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_remote_service_binding(Astcreate_remote_service_binding i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_resource_pool(Astcreate_resource_pool i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_resource_governor(Astalter_resource_governor i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_db_role(Astalter_db_role i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_db_role(Astcreate_db_role i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_route(Astcreate_route i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_rule(Astcreate_rule i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_schema_sql(Astalter_schema_sql i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_schema(Astcreate_schema i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_schema_azure_sql_dw_and_pdw(Astcreate_schema_azure_sql_dw_and_pdw i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_schema_azure_sql_dw_and_pdw(Astalter_schema_azure_sql_dw_and_pdw i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_search_property_list(Astcreate_search_property_list i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_security_policy(Astcreate_security_policy i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_sequence(Astalter_sequence i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_sequence(Astcreate_sequence i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_server_audit(Astalter_server_audit i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_server_audit(Astcreate_server_audit i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_server_audit_specification(Astalter_server_audit_specification i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_server_audit_specification(Astcreate_server_audit_specification i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_server_configuration(Astalter_server_configuration i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_server_role(Astalter_server_role i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_server_role(Astcreate_server_role i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_server_role_pdw(Astalter_server_role_pdw i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_service(Astalter_service i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_service(Astcreate_service i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_service_master_key(Astalter_service_master_key i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_symmetric_key(Astalter_symmetric_key i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_synonym(Astcreate_synonym i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_user(Astalter_user i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_user(Astcreate_user i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_user_azure_sql_dw(Astcreate_user_azure_sql_dw i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_user_azure_sql(Astalter_user_azure_sql i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_workload_group(Astalter_workload_group i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_workload_group(Astcreate_workload_group i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_xml_schema_collection(Astcreate_xml_schema_collection i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_partition_function(Astcreate_partition_function i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_partition_scheme(Astcreate_partition_scheme i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_queue(Astcreate_queue i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitqueue_settings(Astqueue_settings i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_queue(Astalter_queue i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitqueue_action(Astqueue_action i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitqueue_rebuild_options(Astqueue_rebuild_options i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_contract(Astcreate_contract i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitconversation_statement(Astconversation_statement i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitmessage_statement(Astmessage_statement i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitmerge_statement(Astmerge_statement i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitwhen_matches(Astwhen_matches i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitmerge_matched(Astmerge_matched i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitmerge_not_matched(Astmerge_not_matched i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdelete_statement(Astdelete_statement i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdelete_statement_from(Astdelete_statement_from i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitinsert_statement(Astinsert_statement i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitinsert_statement_value(Astinsert_statement_value i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitreceive_statement(Astreceive_statement i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitselect_statement_standalone(Astselect_statement_standalone i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitselect_statement(Astselect_statement i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visittime(Asttime i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitupdate_statement(Astupdate_statement i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitoutput_clause(Astoutput_clause i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitoutput_dml_list_elem(Astoutput_dml_list_elem i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_database(Astcreate_database i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_index(Astcreate_index i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_index_options(Astcreate_index_options i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitrelational_index_option(Astrelational_index_option i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_index(Astalter_index i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitresumable_index_options(Astresumable_index_options i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitresumable_index_option(Astresumable_index_option i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitreorganize_partition(Astreorganize_partition i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitreorganize_options(Astreorganize_options i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitreorganize_option(Astreorganize_option i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitset_index_options(Astset_index_options i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitset_index_option(Astset_index_option i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitrebuild_partition(Astrebuild_partition i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitrebuild_index_options(Astrebuild_index_options i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitrebuild_index_option(Astrebuild_index_option i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitsingle_partition_rebuild_index_options(Astsingle_partition_rebuild_index_options i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitsingle_partition_rebuild_index_option(Astsingle_partition_rebuild_index_option i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visiton_partitions(Aston_partitions i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_columnstore_index(Astcreate_columnstore_index i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_columnstore_index_options(Astcreate_columnstore_index_options i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcolumnstore_index_option(Astcolumnstore_index_option i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_nonclustered_columnstore_index(Astcreate_nonclustered_columnstore_index i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_xml_index(Astcreate_xml_index i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitxml_index_options(Astxml_index_options i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitxml_index_option(Astxml_index_option i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_or_alter_procedure(Astcreate_or_alter_procedure i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitas_external_name(Astas_external_name i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_or_alter_trigger(Astcreate_or_alter_trigger i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_or_alter_dml_trigger(Astcreate_or_alter_dml_trigger i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdml_trigger_option(Astdml_trigger_option i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdml_trigger_operation(Astdml_trigger_operation i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_or_alter_ddl_trigger(Astcreate_or_alter_ddl_trigger i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitddl_trigger_operation(Astddl_trigger_operation i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_or_alter_function(Astcreate_or_alter_function i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitfunc_body_returns_select(Astfunc_body_returns_select i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitfunc_body_returns_table(Astfunc_body_returns_table i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitfunc_body_returns_scalar(Astfunc_body_returns_scalar i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitprocedure_param(Astprocedure_param i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitprocedure_option(Astprocedure_option i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitfunction_option(Astfunction_option i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_statistics(Astcreate_statistics i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitupdate_statistics(Astupdate_statistics i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitupdate_statistics_options(Astupdate_statistics_options i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitupdate_statistics_option(Astupdate_statistics_option i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_table(Astcreate_table i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visittable_indices(Asttable_indices i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visittable_options(Asttable_options i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visittable_option(Asttable_option i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_table_index_options(Astcreate_table_index_options i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_table_index_option(Astcreate_table_index_option i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_view(Astcreate_view i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitview_attribute(Astview_attribute i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_table(Astalter_table i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitswitch_partition(Astswitch_partition i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitlow_priority_lock_wait(Astlow_priority_lock_wait i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_database(Astalter_database i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitadd_or_modify_files(Astadd_or_modify_files i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitfilespec(Astfilespec i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitadd_or_modify_filegroups(Astadd_or_modify_filegroups i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitfilegroup_updatability_option(Astfilegroup_updatability_option i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdatabase_optionspec(Astdatabase_optionspec i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitauto_option(Astauto_option i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitchange_tracking_option(Astchange_tracking_option i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitchange_tracking_option_list(Astchange_tracking_option_list i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcontainment_option(Astcontainment_option i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcursor_option(Astcursor_option i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_endpoint(Astalter_endpoint i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdatabase_mirroring_option(Astdatabase_mirroring_option i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitmirroring_set_option(Astmirroring_set_option i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitmirroring_partner(Astmirroring_partner i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitmirroring_witness(Astmirroring_witness i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitwitness_partner_equal(Astwitness_partner_equal i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitpartner_option(Astpartner_option i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitwitness_option(Astwitness_option i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitwitness_server(Astwitness_server i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitpartner_server(Astpartner_server i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitmirroring_host_port_seperator(Astmirroring_host_port_seperator i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitpartner_server_tcp_prefix(Astpartner_server_tcp_prefix i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitport_number(Astport_number i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visithost(Asthost i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdate_correlation_optimization_option(Astdate_correlation_optimization_option i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdb_encryption_option(Astdb_encryption_option i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdb_state_option(Astdb_state_option i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdb_update_option(Astdb_update_option i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdb_user_access_option(Astdb_user_access_option i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdelayed_durability_option(Astdelayed_durability_option i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitexternal_access_option(Astexternal_access_option i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visithadr_options(Asthadr_options i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitmixed_page_allocation_option(Astmixed_page_allocation_option i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitparameterization_option(Astparameterization_option i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitrecovery_option(Astrecovery_option i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitservice_broker_option(Astservice_broker_option i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitsnapshot_option(Astsnapshot_option i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitsql_option(Astsql_option i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visittarget_recovery_time_option(Asttarget_recovery_time_option i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visittermination(Asttermination i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_index(Astdrop_index i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_relational_or_xml_or_spatial_index(Astdrop_relational_or_xml_or_spatial_index i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_backward_compatible_index(Astdrop_backward_compatible_index i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_procedure(Astdrop_procedure i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_trigger(Astdrop_trigger i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_dml_trigger(Astdrop_dml_trigger i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_ddl_trigger(Astdrop_ddl_trigger i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_function(Astdrop_function i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_statistics(Astdrop_statistics i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_table(Astdrop_table i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_view(Astdrop_view i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_type(Astcreate_type i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdrop_type(Astdrop_type i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitrowset_function_limited(Astrowset_function_limited i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitopenquery(Astopenquery i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitopendatasource(Astopendatasource i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdeclare_statement(Astdeclare_statement i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitxml_declaration(Astxml_declaration i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcursor_statement(Astcursor_statement i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitbackup_database(Astbackup_database i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitbackup_log(Astbackup_log i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitbackup_certificate(Astbackup_certificate i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitbackup_master_key(Astbackup_master_key i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitbackup_service_master_key(Astbackup_service_master_key i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitkill_statement(Astkill_statement i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitkill_process(Astkill_process i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitkill_query_notification(Astkill_query_notification i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitkill_stats_job(Astkill_stats_job i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitexecute_statement(Astexecute_statement i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitexecute_body_batch(Astexecute_body_batch i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitexecute_body(Astexecute_body i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitexecute_statement_arg(Astexecute_statement_arg i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitexecute_statement_arg_named(Astexecute_statement_arg_named i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitexecute_statement_arg_unnamed(Astexecute_statement_arg_unnamed i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitexecute_parameter(Astexecute_parameter i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitexecute_var_string(Astexecute_var_string i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitsecurity_statement(Astsecurity_statement i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitprincipal_id(Astprincipal_id i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_certificate(Astcreate_certificate i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitexisting_keys(Astexisting_keys i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitprivate_key_options(Astprivate_key_options i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitgenerate_new_keys(Astgenerate_new_keys i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdate_options(Astdate_options i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitopen_key(Astopen_key i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitclose_key(Astclose_key i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_key(Astcreate_key i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitkey_options(Astkey_options i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalgorithm(Astalgorithm i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitencryption_mechanism(Astencryption_mechanism i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdecryption_mechanism(Astdecryption_mechanism i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitgrant_permission(Astgrant_permission i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitset_statement(Astset_statement i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visittransaction_statement(Asttransaction_statement i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitgo_statement(Astgo_statement i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visituse_statement(Astuse_statement i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitsetuser_statement(Astsetuser_statement i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitreconfigure_statement(Astreconfigure_statement i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitshutdown_statement(Astshutdown_statement i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcheckpoint_statement(Astcheckpoint_statement i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdbcc_special(Astdbcc_special i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdbcc_clause(Astdbcc_clause i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdbcc_command(Astdbcc_command i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdbcc_options(Astdbcc_options i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitexecute_clause(Astexecute_clause i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdeclare_local(Astdeclare_local i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visittable_type_definition(Asttable_type_definition i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visittable_type_indices(Asttable_type_indices i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitxml_type_definition(Astxml_type_definition i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitxml_schema_collection(Astxml_schema_collection i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcolumn_def_table_constraints(Astcolumn_def_table_constraints i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcolumn_def_table_constraint(Astcolumn_def_table_constraint i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcolumn_definition(Astcolumn_definition i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcolumn_definition_element(Astcolumn_definition_element i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcolumn_modifier(Astcolumn_modifier i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitmaterialized_column_definition(Astmaterialized_column_definition i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcolumn_constraint(Astcolumn_constraint i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcolumn_index(Astcolumn_index i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visiton_partition_or_filegroup(Aston_partition_or_filegroup i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visittable_constraint(Asttable_constraint i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitconnection_node(Astconnection_node i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitprimary_key_options(Astprimary_key_options i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitforeign_key_options(Astforeign_key_options i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcheck_constraint(Astcheck_constraint i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visiton_delete(Aston_delete i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visiton_update(Aston_update i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_table_index_options(Astalter_table_index_options i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitalter_table_index_option(Astalter_table_index_option i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdeclare_cursor(Astdeclare_cursor i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdeclare_set_cursor_common(Astdeclare_set_cursor_common i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdeclare_set_cursor_common_partial(Astdeclare_set_cursor_common_partial i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitfetch_cursor(Astfetch_cursor i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitset_special(Astset_special i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitspecial_list(Astspecial_list i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitconstant_LOCAL_ID(Astconstant_LOCAL_ID i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitexpression(Astexpression i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitparameter(Astparameter i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visittime_zone(Asttime_zone i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitprimitive_expression(Astprimitive_expression i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcase_expression(Astcase_expression i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitunary_operator_expression(Astunary_operator_expression i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitbracket_expression(Astbracket_expression i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitconstant_expression(Astconstant_expression i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitsubquery(Astsubquery i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitwith_expression(Astwith_expression i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcommon_table_expression(Astcommon_table_expression i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitupdate_elem(Astupdate_elem i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitupdate_elem_merge(Astupdate_elem_merge i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitsearch_condition(Astsearch_condition i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitpredicate(Astpredicate i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitquery_expression(Astquery_expression i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitsql_union(Astsql_union i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitquery_specification(Astquery_specification i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visittop_clause(Asttop_clause i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visittop_percent(Asttop_percent i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visittop_count(Asttop_count i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitorder_by_clause(Astorder_by_clause i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitselect_order_by_clause(Astselect_order_by_clause i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitfor_clause(Astfor_clause i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitxml_common_directives(Astxml_common_directives i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitorder_by_expression(Astorder_by_expression i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitgrouping_sets_item(Astgrouping_sets_item i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitgroup_by_item(Astgroup_by_item i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitoption_clause(Astoption_clause i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitoption(Astoption i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitoptimize_for_arg(Astoptimize_for_arg i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitselect_list(Astselect_list i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitudt_method_arguments(Astudt_method_arguments i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitasterisk(Astasterisk i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcolumn_elem(Astcolumn_elem i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitudt_elem(Astudt_elem i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitexpression_elem(Astexpression_elem i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitselect_list_elem(Astselect_list_elem i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visittable_sources(Asttable_sources i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visittable_source(Asttable_source i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visittable_source_item_joined(Asttable_source_item_joined i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visittable_source_item(Asttable_source_item i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitopen_xml(Astopen_xml i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitopen_json(Astopen_json i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitjson_declaration(Astjson_declaration i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitjson_column_declaration(Astjson_column_declaration i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitschema_declaration(Astschema_declaration i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcolumn_declaration(Astcolumn_declaration i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitchange_table(Astchange_table i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitchange_table_changes(Astchange_table_changes i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitchange_table_version(Astchange_table_version i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitjoin_part(Astjoin_part i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitjoin_on(Astjoin_on i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcross_join(Astcross_join i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitapply_(Astapply_ i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitpivot(Astpivot i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitunpivot(Astunpivot i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitpivot_clause(Astpivot_clause i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitunpivot_clause(Astunpivot_clause i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitfull_column_name_list(Astfull_column_name_list i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitrowset_function(Astrowset_function i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitbulk_option(Astbulk_option i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitderived_table(Astderived_table i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitfunction_call(Astfunction_call i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitpartition_function(Astpartition_function i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitfreetext_function(Astfreetext_function i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitfreetext_predicate(Astfreetext_predicate i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitbuilt_in_functions(Astbuilt_in_functions i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitxml_data_type_methods(Astxml_data_type_methods i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitvalue_method(Astvalue_method i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitvalue_call(Astvalue_call i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitquery_method(Astquery_method i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitquery_call(Astquery_call i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitexist_method(Astexist_method i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitexist_call(Astexist_call i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitmodify_method(Astmodify_method i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitmodify_call(Astmodify_call i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visithierarchyid_call(Asthierarchyid_call i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visithierarchyid_static_method(Asthierarchyid_static_method i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitnodes_method(Astnodes_method i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitswitch_section(Astswitch_section i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitswitch_search_condition_section(Astswitch_search_condition_section i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitas_column_alias(Astas_column_alias i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitas_table_alias(Astas_table_alias i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visittable_alias(Asttable_alias i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitwith_table_hints(Astwith_table_hints i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdeprecated_table_hint(Astdeprecated_table_hint i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitsybase_legacy_hints(Astsybase_legacy_hints i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitsybase_legacy_hint(Astsybase_legacy_hint i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visittable_hint(Asttable_hint i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitindex_value(Astindex_value i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcolumn_alias_list(Astcolumn_alias_list i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcolumn_alias(Astcolumn_alias i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visittable_value_constructor(Asttable_value_constructor i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitexpression_list(Astexpression_list i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitranking_windowed_function(Astranking_windowed_function i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitaggregate_windowed_function(Astaggregate_windowed_function i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitanalytic_windowed_function(Astanalytic_windowed_function i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitall_distinct_expression(Astall_distinct_expression i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitover_clause(Astover_clause i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitrow_or_range_clause(Astrow_or_range_clause i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitwindow_frame_extent(Astwindow_frame_extent i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitwindow_frame_bound(Astwindow_frame_bound i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitwindow_frame_preceding(Astwindow_frame_preceding i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitwindow_frame_following(Astwindow_frame_following i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcreate_database_option(Astcreate_database_option i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdatabase_filestream_option(Astdatabase_filestream_option i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdatabase_file_spec(Astdatabase_file_spec i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitfile_group(Astfile_group i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitfile_spec(Astfile_spec i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitentity_name(Astentity_name i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitentity_name_for_azure_dw(Astentity_name_for_azure_dw i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitentity_name_for_parallel_dw(Astentity_name_for_parallel_dw i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitfull_table_name(Astfull_table_name i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visittable_name(Asttable_name i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitsimple_name(Astsimple_name i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitfunc_proc_name_schema(Astfunc_proc_name_schema i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitfunc_proc_name_database_schema(Astfunc_proc_name_database_schema i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitfunc_proc_name_server_database_schema(Astfunc_proc_name_server_database_schema i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitddl_object(Astddl_object i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitfull_column_name(Astfull_column_name i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcolumn_name_list_with_order(Astcolumn_name_list_with_order i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitinsert_column_name_list(Astinsert_column_name_list i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitinsert_column_id(Astinsert_column_id i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcolumn_name_list(Astcolumn_name_list i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcursor_name(Astcursor_name i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visiton_off(Aston_off i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitclustered(Astclustered i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitnull_notnull(Astnull_notnull i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitnull_or_default(Astnull_or_default i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitscalar_function_name(Astscalar_function_name i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitbegin_conversation_timer(Astbegin_conversation_timer i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitbegin_conversation_dialog(Astbegin_conversation_dialog i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcontract_name(Astcontract_name i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitservice_name(Astservice_name i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitend_conversation(Astend_conversation i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitwaitfor_conversation(Astwaitfor_conversation i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitget_conversation(Astget_conversation i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitqueue_id(Astqueue_id i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitsend_conversation(Astsend_conversation i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdata_type(Astdata_type i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitdefault_value(Astdefault_value i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitconstant(Astconstant i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitsign(Astsign i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitkeyword(Astkeyword i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitid_(Astid_ i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitsimple_id(Astsimple_id i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitid_or_string(Astid_or_string i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitcomparison_operator(Astcomparison_operator i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitassignment_operator(Astassignment_operator i);
    }
    
    public partial interface ITSqlVisitor : IAstBaseVisitor {
        
        Bb.Asts.AstBase Visitfile_size(Astfile_size i);
    }
}
